### ISSUE TITLE
Avoid Holidays Quotes

### ISSUE THREAD

**Issue by ForosArgBursatil** [drbeep/yahoo_datafeed#3]
Hi Ruslan! Is it possible to filter those days when Volume = 0 and Open=Close=Max=Min
That happens in Yahoo Finance when there is a holiday.
Can you give me clue what part of the code should I edit?

I send a preview:
![holidays](https://cloud.githubusercontent.com/assets/8614903/6197581/ad635778-b3c6-11e4-895e-3b37dab5071c.jpg)

Thank you!

**Comment by drbeep** [comment]
Sure. Just put a condition on `volume === 0` somewhere near the line # 58 and just skip those bars.

**Comment by ForosArgBursatil** [comment]
In yahoo.js file?
I don't know how. Sorry.

**Comment by drbeep** [comment]
Yes, in `yahoo.js`.

**Comment by ForosArgBursatil** [comment]
I'm getting stuck with this...
Yahoo Finance doesn't filter holidays events in some exchanges, i.e. Merval.
The following picture shows another example, where there is 4 days and each have volume = 0 and the close price is the same as previous day.
![graph](https://cloud.githubusercontent.com/assets/8614903/7105993/817c0248-e109-11e4-828e-2ee16b7cb146.jpg)
I'm pretty sure that the filtering condition must be:
CLOSE TODAY = CLOSE YERTERDAY AND VOLUME =0 
Both conditions at the same time.
I'd very gratefull if someone help me with the exact codeline I shoud add for this.

Thank you!

**Comment by drbeep** [comment]
Well, try to replace the function `convertYahooHistoryToUDFFormat` (yahoo.js, 40) with the following

```
function convertYahooHistoryToUDFFormat(data) {

	function parseDate(input) {
		var parts = input.split('-');
		return Date.UTC(parts[0], parts[1]-1, parts[2]);
	}
	var result = {
		t: [], c: [], o: [], h: [], l: [], v: [],
		s: "ok"
	};
	
	var prevClose;
	var lines = data.split('\n');
	for (var i = lines.length - 2; i > 0; --i) {
		var items = lines[i].split(",");
		var time = parseDate(items[0]) / 1000;

		var ohlc = {
			open: parseFloat(items[1]),
			high: parseFloat(items[2]),
			low: parseFloat(items[3]),
			close: parseFloat(items[4]),
			volume: parseInt(items[5])
		};

		if (prevClose && prevClose == ohlc.close && ohlc.volume == 0) {
			continue;
		}

		prevClose = ohlc.close;

		result.t.push(time);
		result.o.push(ohlc.open);
		result.h.push(ohlc.high);
		result.l.push(ohlc.low);
		result.c.push(ohlc.close);
		result.v.push(ohlc.volume);
	}
	return result;
}
```

I did not test this code, but it should work.

**Comment by ForosArgBursatil** [comment]
Works great!!! Thank very much!

**Comment by drbeep** [comment]
Glad to help.
